import type { ActionResult, Entity, GameState, LeafId, LifeState, Vec } from './contracts';
export const clone=<T>(v:T):T=>JSON.parse(JSON.stringify(v));
export function createLifeState():LifeState{return {repair:{stage:'unaccepted',softened:false,stopSet:false,latched:false,tested:false,method:null,testing:null},harvest:{stage:'unaccepted',sun:'unpicked',shade:'unpicked',picking:null,shared:false},clamp:'unowned',sachets:0,scent:null};}
const d=(a:Vec,b:Vec)=>Math.hypot(a.x-b.x,a.y-b.y);
export function lifeUnlocked(s:GameState):boolean{return (s.flags.endingWish==='stay'||s.flags.endingWish==='travel')&&s.ended;}
export function lifeObjective(s:GameState):string|undefined{if(!lifeUnlocked(s))return undefined;if(s.life.repair.stage==='complete'&&s.life.harvest.stage==='complete')return '手艺与行囊已经备好；可继续试术，或在桌边歇一歇';if(s.life.repair.stage!=='complete')return s.life.repair.stage==='unaccepted'?'陶七有一枚备用挂扣，想请你修到能承重':'先把挂扣炉芯、活动钳口和压柄做完';return s.life.harvest.stage==='unaccepted'?'许照想给晒架添两束叶':'把两束叶带回并分到晒架上';}
export function lifeDescription(s:GameState,e:Entity):string|undefined{if(!lifeUnlocked(s)||!e.id.startsWith('life_'))return undefined;if(e.id==='life_sun_leaf'||e.id==='life_shade_leaf')return '剪上部叶片，根仍留在石边；需要近身停稳两秒。';if(e.id==='life_jaw')return s.life.repair.softened?'沿横向导轨校直到刻线处。':'先把挂扣装进炉芯，再用火球软化旧胶。';if(e.id==='life_press')return s.life.repair.latched?'再次近身操作，保持一秒完成试压。':'靠近压柄，可拨止挡或用留势支承钳口。';return e.name;}
export function beginPicking(s:GameState,id:LeafId):ActionResult{if(s.scene!=='creek'||s.life.harvest.stage!=='active'||s.life.harvest.picking)return {ok:false,message:'现在不能采叶'};const key=id==='life_sun_leaf'?'sun':'shade';if(s.life.harvest[key]!=='unpicked')return {ok:false,message:'这束叶已经剪过'};const e=s.worlds.creek.find(x=>x.id===id);if(!e||e.state==='picked'||d(s.player,e)>96)return {ok:false,message:'需要靠近叶簇'};s.life.harvest.picking={id,elapsed:0,start:{x:s.player.x,y:s.player.y}};return {ok:true};}
export function lifeTick(s:GameState,dt:number):void{if(s.paused||dt<=0)return;const p=s.life.harvest.picking;if(p){if(d(s.player,p.start)>4){s.life.harvest.picking=null;return;}p.elapsed+=dt;if(p.elapsed>=2){const k=p.id==='life_sun_leaf'?'sun':'shade';s.life.harvest[k]='bag';s.life.harvest.picking=null;const e=s.worlds.creek.find(x=>x.id===p.id);if(e)e.state='picked';if(s.life.harvest.sun!=='unpicked'&&s.life.harvest.shade!=='unpicked')s.life.harvest.stage='ready';}}if(s.life.scent){s.life.scent.remaining=Math.max(0,s.life.scent.remaining-dt);if(!s.life.scent.remaining){s.life.scent=null;const e=s.worlds.workshop.find(x=>x.id==='life_scent');if(e)e.state='hidden';}}}
export function useSachet(s:GameState):ActionResult{if(s.scene!=='workshop'||s.life.sachets===0||s.life.scent)return {ok:false,message:'此处不能再放药囊'};const e=s.worlds.workshop.find(x=>x.id==='life_scent');if(!e)return {ok:false,message:'药囊实体缺失'};e.x=s.player.x;e.y=s.player.y+22;e.state='idle';s.life.scent={remaining:8};s.life.sachets=(s.life.sachets-1) as 0|1;return {ok:true,message:'药囊落在脚边，气味开始扩散'};}
