/// <reference types="vite/client" />
import {describe,it,expect} from 'vitest';
import main02 from '../qa/fixtures/return-main-v0.2.2.json?raw';
import ridge02 from '../qa/fixtures/return-ridge-v0.2.2.json?raw';
import main03 from '../qa/fixtures/return-main-v0.3.0.json?raw';
import ridge03 from '../qa/fixtures/return-ridge-v0.3.0.json?raw';
import {restore,snapshot} from '../src/game/save';
import {act} from '../src/game/model';
import type {GameState} from '../src/game/contracts';

const current=()=>restore(main03);
const round=(s:GameState)=>restore(snapshot(s));
const entity=(s:GameState,id:string)=>Object.values(s.worlds).flat().find(e=>e.id===id)!;
function harvested(s:GameState){Object.assign(s.life.harvest,{stage:'complete',sun:'upper',shade:'lower'});entity(s,'life_sun_leaf').state=entity(s,'life_shade_leaf').state='picked';s.life.sachets=1;return s;}
function repaired(s:GameState){Object.assign(s.life.repair,{stage:'complete',softened:true,stopSet:true,latched:true,tested:true,method:'stop'});Object.assign(entity(s,'life_jaw'),{state:'latched',x:1420,y:570});s.life.clamp='bag';return s;}

describe('canal content 3 saves',()=>{
 for(const [label,raw] of [['main 0.2',main02],['ridge 0.2',ridge02],['main 0.3',main03],['ridge 0.3',ridge03]])it(`migrates real ${label} export and checkpoint without changing prior outcomes or resources`,()=>{
  const old=JSON.parse(raw),s=restore(raw),nested=JSON.parse(s.checkpoint!),oldNested=JSON.parse(old.checkpoint);
  for(const [next,prior] of [[s,old],[nested,oldNested]]){expect(next.contentVersion).toBe(5);expect(next.player).toEqual(prior.player);expect(next.flags).toEqual(prior.flags);expect(next.ended).toBe(prior.ended);expect(next.canal.stage).toBe('unaccepted');expect(next.canal.cleared).toBe(false);expect(next.canal.work).toBeNull();expect(next.worlds.canal.length).toBeGreaterThan(10);if(prior.life)expect(next.life).toEqual(prior.life);for(const scene of ['home','creek','workshop','crossing'])for(const e of prior.worlds[scene])expect(next.worlds[scene].find((n:{id:string})=>n.id===e.id)).toEqual(e);}
  expect(nested.checkpoint).toBeNull();expect(snapshot(round(s))).toBe(snapshot(s));
 });
 it('upgrades an active old workshop scent in place and preserves its timer and spent amount',()=>{const old=harvested(current()) as unknown as Record<string,any>;delete old.kiln;delete old.worlds.kiln;old.worlds.creek=old.worlds.creek.filter((e:{id:string})=>e.id!=='creek_to_kiln');delete old.journey;for(const scene of Object.keys(old.worlds))old.worlds[scene]=old.worlds[scene].filter((e:{id:string})=>!e.id.startsWith('journey_'));delete old.canal;delete old.worlds.canal;old.contentVersion=2;old.checkpoint=null;old.life.scent={remaining:3.25};Object.assign(old.worlds.workshop.find((e:{id:string})=>e.id==='life_scent'),{state:'idle',x:777,y:555});const s=restore(JSON.stringify(old));expect(s.life.scent).toEqual({remaining:3.25,scene:'workshop'});expect(s.life.sachets).toBe(1);expect(entity(s,'life_scent')).toMatchObject({x:777,y:555,state:'idle'});expect(entity(s,'canal_scent').state).toBe('hidden');});
 for(const version of [0,1,6,'3',null])it(`rejects unknown version ${version}`,()=>{const s=JSON.parse(main03);s.contentVersion=version;expect(()=>restore(JSON.stringify(s))).toThrow();});
 for(const raw of [main02,main03])it('rejects extra scenes in older manifests instead of silently replacing them',()=>{const old=JSON.parse(raw);old.worlds.canal=[];expect(()=>restore(JSON.stringify(old))).toThrow();});
 it('validates nested new progress through the same rules',()=>{const s=current(),nested=JSON.parse(s.checkpoint!);nested.canal.stage='ready';s.checkpoint=JSON.stringify(nested);expect(()=>round(s)).toThrow();});
 it('rejects a content 3 save missing its canal ledger',()=>{const s=current();delete (s as Partial<GameState>).canal;expect(()=>round(s)).toThrow();});
 it('rejects replacing the new screen with an unknown entity',()=>{const s=current();entity(s,'canal_screen').id='unknown-screen';expect(()=>round(s)).toThrow();});
 for(const field of ['scene','lastSafe'] as const)it(`rejects ${field} in canal before accepting the invitation`,()=>{const s=current();if(field==='scene')s.scene='canal';else s.lastSafe.scene='canal';expect(()=>round(s)).toThrow();});
 for(const id of ['canal_diverter','canal_stop'])for(const axis of ['x','y'] as const)it(`rejects ${id} off its ${axis} rail`,()=>{const s=current();s.canal.stage='active';entity(s,id)[axis]+=100;expect(()=>round(s)).toThrow();});
 it('rejects a clear supported only by an obsolete dry timer',()=>{const s=current();s.scene='canal';s.canal.stage='active';s.canal.inspected=true;s.canal.drain=1;Object.assign(s.player,{x:1130,y:510});s.canal.work={kind:'clear',elapsed:.3,start:{x:1130,y:510}};expect(()=>round(s)).toThrow();});
 it('preserves a real held stop with no live pull point and fractional timers',()=>{const s=current();s.scene='canal';s.canal.stage='active';s.canal.inspected=true;s.canal.drain=.45;Object.assign(s.player,{x:1230,y:410,pullId:'canal_stop',pullPoint:null,hold:5.2});Object.assign(entity(s,'canal_stop'),{x:1200,y:350,state:'held'});expect(round(s).player).toEqual(s.player);expect(round(s).canal).toEqual(s.canal);});
 it('preserves a paused manual operation without advancing work or water',()=>{const s=current();s.scene='canal';s.paused=true;s.canal.stage='active';Object.assign(s.player,{x:600,y:410});s.canal.work={kind:'divert',elapsed:1.35,start:{x:600,y:410}};expect(round(s).canal).toEqual(s.canal);expect(round(s).paused).toBe(true);});
 it('preserves an unfinished clear while held support leaves both hands free',()=>{const s=current();s.scene='canal';s.canal.stage='active';s.canal.inspected=true;s.canal.drain=1;Object.assign(s.player,{x:1130,y:510,pullId:'canal_stop',pullPoint:null,hold:3.6});Object.assign(entity(s,'canal_stop'),{x:1200,y:350,state:'held'});s.canal.work={kind:'clear',elapsed:1.1,start:{x:1130,y:510}};expect(round(s).canal.work).toEqual(s.canal.work);});
 it('can save immediately after releasing support during a clear, before another tick',()=>{const s=current();s.scene='canal';s.paused=false;s.dialogue=null;s.canal.stage='active';s.canal.inspected=true;s.canal.drain=1;Object.assign(s.player,{x:1130,y:510,pullId:'canal_stop',pullPoint:null,hold:3.6});Object.assign(entity(s,'canal_stop'),{x:1200,y:350,state:'held'});s.canal.work={kind:'clear',elapsed:1.1,start:{x:1130,y:510}};act(s,{type:'release'});act(s,{type:'pause',value:true});expect(s.canal.work).toBeNull();expect(round(s).canal).toEqual(s.canal);});
 it('keeps completion historical when the water is diverted again',()=>{const s=current();Object.assign(s.canal,{stage:'complete',inspected:true,cleared:true,method:'diversion',drain:.6});entity(s,'canal_screen').state='cleared';entity(s,'canal_rest_mid').state='idle';entity(s,'canal_diverter').x=680;expect(round(s).canal).toEqual(s.canal);});
 it('preserves a single canal clamp after leaving the map',()=>{const s=repaired(current());s.canal.stage='active';s.canal.usedClamp=true;s.life.clamp='canal';Object.assign(entity(s,'canal_stop'),{x:1200,y:350,state:'clamped'});expect(round(s).life.clamp).toBe('canal');});
 for(const defect of ['double','position','held'])it(`rejects canal clamp ${defect}`,()=>{const s=repaired(current());s.canal.stage='active';s.canal.usedClamp=true;s.life.clamp='canal';Object.assign(entity(s,'canal_stop'),{x:1200,y:350,state:'clamped'});if(defect==='double')Object.assign(entity(s,'life_practice'),{x:1030,y:500,state:'clamped'});if(defect==='position')entity(s,'canal_stop').x=1280;if(defect==='held'){s.scene='canal';s.player.pullId='canal_stop';s.player.pullPoint=null;s.player.hold=4;}expect(()=>round(s)).toThrow();});
 it('preserves one canal scent in its own world while the player is elsewhere',()=>{const s=harvested(current());s.canal.stage='active';s.life.scent={scene:'canal',remaining:6.5};Object.assign(entity(s,'canal_scent'),{state:'idle',x:1500,y:600});expect(round(s).life.scent).toEqual(s.life.scent);});
 for(const defect of ['double','wrong-world','unknown-world','missing-scene'])it(`rejects scent ${defect}`,()=>{const s=harvested(current());s.canal.stage='active';s.life.scent={scene:'canal',remaining:6.5};entity(s,'canal_scent').state='idle';if(defect==='double')entity(s,'life_scent').state='idle';if(defect==='wrong-world'){entity(s,'canal_scent').state='hidden';entity(s,'life_scent').state='idle';}if(defect==='unknown-world')Object.assign(s.life.scent,{scene:'home'});if(defect==='missing-scene')delete (s.life.scent as Partial<typeof s.life.scent>).scene;expect(()=>round(s)).toThrow();});
 for(const defect of ['unaccepted-progress','verified-uncleared','cleared-no-method','screen-mismatch','timer','work-scene','work-distance','work-held'])it(`rejects invalid canal process ${defect}`,()=>{const s=current();s.canal.stage='active';if(defect==='unaccepted-progress'){s.canal.stage='unaccepted';s.canal.inspected=true;}if(defect==='verified-uncleared')s.canal.stage='verified';if(defect==='cleared-no-method'){s.canal.inspected=true;s.canal.cleared=true;entity(s,'canal_screen').state='cleared';}if(defect==='screen-mismatch')entity(s,'canal_screen').state='cleared';if(defect==='timer')s.canal.drain=2;if(defect.startsWith('work-')){s.scene='canal';Object.assign(s.player,{x:600,y:410});s.canal.work={kind:'divert',elapsed:.5,start:{x:600,y:410}};if(defect==='work-scene')s.scene='home';if(defect==='work-distance')s.canal.work.start.x=0;if(defect==='work-held'){s.player.pullId='canal_diverter';s.player.pullPoint={x:650,y:350};}}expect(()=>round(s)).toThrow();});
});
