import { describe, it, expect } from 'vitest';
import { createGame, act, tick, snapshot, restore } from '../src/game/model';
import type { GameState } from '../src/game/contracts';
const profile={name:'行舟',origin:'tinker' as const,wish:'travel' as const,appearance:0 as const};
const advance=(s:GameState,t:number)=>{for(let i=0;i<Math.ceil(t/.05);i++)tick(s,.05,{x:0,y:0});};
const get=(s:GameState,id:string)=>s.worlds[s.scene].find(e=>e.id===id)!;
function finished(){const s=createGame(profile);s.ended=true;s.flags.endingWish='travel';s.flags.ringOwned=true;s.flags.ringTrained=true;s.ringStyle='long';return s;}
function choice(s:GameState,id:string){for(let i=0;i<8&&!s.dialogue?.choices.some(c=>c.id===id);i++)act(s,{type:'choose',choiceId:'more'});return act(s,{type:'choose',choiceId:id});}
function acceptRepair(s:GameState){s.scene='home';s.player.x=480;s.player.y=660;expect(act(s,{type:'interact',targetId:'tao'}).ok).toBe(true);expect(choice(s,'life:repair:accept').ok).toBe(true);s.scene='workshop';s.player.x=1380;s.player.y=485;}
function heat(s:GameState){expect(act(s,{type:'interact',targetId:'life_hearth'}).ok).toBe(true);expect(act(s,{type:'cast',spell:'flame',targetId:'life_hearth',point:{x:1320,y:430}}).ok).toBe(true);advance(s,1);expect(s.life.repair.softened).toBe(true);}
function jaw(s:GameState){s.player.x=1410;s.player.y=620;expect(act(s,{type:'cast',spell:'pull',targetId:'life_jaw',point:{x:1420,y:570}}).ok).toBe(true);advance(s,.5);expect(get(s,'life_jaw').x).toBeCloseTo(1420,0);}
function pressure(s:GameState){expect(act(s,{type:'interact',targetId:'life_press'}).ok).toBe(true);expect(s.life.repair.latched).toBe(true);act(s,{type:'release'});expect(act(s,{type:'interact',targetId:'life_press'}).ok).toBe(true);advance(s,1.1);expect(s.life.repair.stage).toBe('ready');}
describe('home-life actual model actions',()=>{
 it('keeps commissions locked before the real table ending',()=>{const s=createGame(profile);s.player.x=480;s.player.y=660;act(s,{type:'interact',targetId:'tao'});expect(choice(s,'life:repair:accept').ok).toBe(false);expect(s.life.repair.stage).toBe('unaccepted');});
 it('repairs with a mechanical stop and rewards once, only after actual pressure test',()=>{const s=finished();acceptRepair(s);expect(act(s,{type:'interact',targetId:'life_press'}).ok).toBe(false);heat(s);s.player.x=1410;s.player.y=620;act(s,{type:'interact',targetId:'life_press'});expect(choice(s,'life:repair:stop').ok).toBe(true);jaw(s);act(s,{type:'release'});advance(s,.5);expect(get(s,'life_jaw').x).toBeCloseTo(1420,0);pressure(s);s.scene='home';s.player.x=480;s.player.y=660;act(s,{type:'interact',targetId:'tao'});expect(choice(s,'life:repair:deliver').ok).toBe(true);expect(s.life.clamp).toBe('bag');expect(choice(s,'life:repair:deliver').ok).toBe(false);expect(restore(snapshot(s)).life.clamp).toBe('bag');});
 it('uses hold without stop; pause freezes support and pressure needs a free hand',()=>{const s=finished();acceptRepair(s);heat(s);s.ringStyle='hold';jaw(s);expect(act(s,{type:'interact',targetId:'life_press'}).ok).toBe(false);act(s,{type:'hold'});act(s,{type:'pause',value:true});advance(s,9);expect(s.player.hold).toBe(8);act(s,{type:'pause',value:false});pressure(s);expect(s.life.repair.method).toBe('hold');});
 it('an unsupported released jaw returns and cannot certify itself',()=>{const s=finished();acceptRepair(s);heat(s);jaw(s);act(s,{type:'release'});advance(s,1);expect(get(s,'life_jaw').x).toBe(1360);expect(s.life.repair.tested).toBe(false);});
 it('collects shade from safe east with no mana, pauses and movement cancel correctly',()=>{const s=finished();s.scene='home';s.player.x=1120;s.player.y=710;act(s,{type:'interact',targetId:'xu'});expect(choice(s,'life:harvest:accept').ok).toBe(true);s.scene='creek';s.player.x=1455;s.player.y=680;s.player.mana=0;expect(act(s,{type:'interact',targetId:'life_shade_leaf'}).ok).toBe(true);act(s,{type:'pause',value:true});advance(s,3);expect(s.life.harvest.shade).toBe('unpicked');act(s,{type:'pause',value:false});advance(s,.5);act(s,{type:'move',point:{x:1480,y:700}});advance(s,2);expect(s.life.harvest.shade).toBe('unpicked');s.player.x=1455;s.player.y=680;s.player.path=[];act(s,{type:'interact',targetId:'life_shade_leaf'});advance(s,2.1);expect(s.life.harvest.shade).toBe('bag');expect(s.player.hp).toBe(4);expect(s.life.sachets).toBe(0);});
});
