import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {readFile,readdir,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
const base='https://mekanuo.github.io/xian-ni-game/';
const evidence={checkedAt:new Date().toISOString(),url:base,release:null,resources:[],browser:null,input:[],errors:[]};
const releaseResponse=await fetch(new URL('release.json',base));assert.equal(releaseResponse.status,200);evidence.release=await releaseResponse.json();
assert.equal(evidence.release.version,JSON.parse(await readFile('package.json','utf8')).version,'Public release must be the current version');
async function files(dir){const list=[];for(const e of await readdir(dir,{withFileTypes:true})){const path=`${dir}/${e.name}`;if(e.isDirectory())list.push(...await files(path));else list.push(path);}return list;}
const hash=b=>createHash('sha256').update(b).digest('hex');
evidence.resources=await Promise.all((await files('dist')).map(async path=>{const relative=path.slice(5),response=await fetch(new URL(relative,base));assert.equal(response.status,200,relative);const bytes=Buffer.from(await response.arrayBuffer()),local=await readFile(path);assert.equal(hash(bytes),hash(local),`${relative} must match the tested production build`);return {path:relative,status:response.status,bytes:bytes.length,sha256:hash(bytes)};}));
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});
try{
const page=await browser.newPage({viewport:{width:1440,height:900}});page.on('pageerror',e=>evidence.errors.push(e.message));evidence.browser=await browser.version();
await page.goto(base);await page.getByRole('button',{name:'入 山',exact:true}).click();await page.getByRole('button',{name:'去回石驿',exact:true}).click();
await page.waitForFunction(()=>window.__XIAN_NI__.audio().musicRms>.002);
evidence.audio=await page.evaluate(()=>window.__XIAN_NI__.audio());
const state=()=>page.evaluate(()=>{const s=window.__XIAN_NI__.inspect();return {scene:s.scene,player:s.player,flags:s.flags,ended:s.ended};});
evidence.input.push({action:'create profile on public site',state:await state()});
await page.locator('[data-ui="spell:pull"]').click();let point=await page.evaluate(()=>window.__XIAN_NI__.screenPoint(430,760));await page.mouse.click(point.x,point.y);await page.waitForFunction(()=>window.__XIAN_NI__.inspect().player.pullId==='lamp');
point=await page.evaluate(()=>window.__XIAN_NI__.screenPoint(560,665));await page.mouse.click(point.x,point.y);await page.waitForFunction(()=>{const s=window.__XIAN_NI__.inspect(),e=s.worlds.home.find(e=>e.id==='lamp');return Math.hypot(e.x-560,e.y-665)<10;});await page.locator('[data-ui="release"]').click();assert.equal((await state()).flags.lampFixed,true);
evidence.input.push({action:'click pull, lamp, stand and release',state:await state()});
const before=(await state()).player.x;await page.keyboard.down('d');await page.waitForTimeout(750);await page.keyboard.up('d');assert.ok((await state()).player.x>before+20);
evidence.input.push({action:'keyboard D movement',state:await state()});
await page.locator('[data-ui="observe"]').click();assert.equal(await page.locator('[data-ui="observe"]').getAttribute('aria-expanded'),'true');evidence.input.push({action:'open current encounter observation',text:await page.locator('#observation-content').textContent()});
await page.screenshot({path:'qa/evidence/public-start.png'});evidence.visual='qa/evidence/public-start.png';assert.equal(evidence.errors.length,0);
// Verify the new public continuation through the same real old-save import UI.
await page.locator('[data-ui="settings"]').click();
await page.locator('#import-save').setInputFiles('qa/fixtures/return-main-v0.2.2.json');
await page.waitForFunction(()=>window.__XIAN_NI__.inspect().ended&&window.__XIAN_NI__.inspect().contentVersion===2);
const oldEnding=page.getByRole('button',{name:'在驿中再坐一会儿',exact:true});if(await oldEnding.isVisible())await oldEnding.click();
if(await page.evaluate(()=>window.__XIAN_NI__.inspect().paused))await page.locator('.action-dock [data-ui="pause"]').click();
point=await page.evaluate(()=>window.__XIAN_NI__.screenPoint(1060,430));await page.mouse.click(point.x,point.y);
await page.waitForFunction(()=>window.__XIAN_NI__.inspect().dialogue!==null,null,{timeout:30000});
for(let i=0;i<12&&!await page.evaluate(()=>window.__XIAN_NI__.inspect().dialogue?.choices.some(c=>c.id==='life:repair:accept'));i++)await page.locator('[data-ui="choice:more"]').click();
await page.locator('[data-ui="choice:life:repair:accept"]').click();
await page.waitForFunction(()=>window.__XIAN_NI__.inspect().life.repair.stage==='active');
evidence.continuation=await page.evaluate(()=>{const s=window.__XIAN_NI__.inspect();return {contentVersion:s.contentVersion,checkpointVersion:JSON.parse(s.checkpoint).contentVersion,life:s.life,fixture:'Real 0.2.2 main ending imported via settings',input:'Click workbench, accept repair'};});
await page.screenshot({path:'qa/evidence/public-life.png'});
await page.close();
const phoneContext=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:3,isMobile:true,hasTouch:true});
const phone=await phoneContext.newPage();phone.on('pageerror',e=>evidence.errors.push(e.message));
await phone.goto(base);await phone.getByRole('button',{name:'入 山',exact:true}).tap();await phone.getByRole('button',{name:'去回石驿',exact:true}).tap();
await phone.waitForFunction(()=>window.__XIAN_NI__.audio().musicRms>.002);
const phoneDimensions=await phone.evaluate(()=>{const c=document.querySelector('canvas');return {pixels:[c.width,c.height],css:[c.clientWidth,c.clientHeight],dpr:devicePixelRatio};});
assert.deepEqual(phoneDimensions.pixels,[1170,2532]);
await phone.locator('[data-ui="spell:ward"]').tap();
const wardPoint=await phone.evaluate(()=>{const p=window.__XIAN_NI__.inspect().player;return window.__XIAN_NI__.screenPoint(p.x+85,p.y-10);});
await phone.touchscreen.tap(wardPoint.x,wardPoint.y);await phone.waitForFunction(()=>window.__XIAN_NI__.inspect().player.ward>0&&window.__XIAN_NI__.audio().effectCounts.ward>=1);
evidence.mobile={device:'Chrome touch / DPR3 emulation, not a physical phone',dimensions:phoneDimensions,audio:await phone.evaluate(()=>window.__XIAN_NI__.audio()),input:'tap create, select ward, tap cast direction',visual:'qa/evidence/public-mobile.png'};
await phone.locator('[data-ui="observe"]').tap();assert.equal(await phone.locator('[data-ui="observe"]').getAttribute('aria-expanded'),'true');evidence.mobile.observation=await phone.locator('#observation-content').textContent();
await phone.screenshot({path:evidence.mobile.visual});await phoneContext.close();assert.equal(evidence.errors.length,0);
await writeFile('qa/evidence/publication.json',JSON.stringify(evidence,null,2));console.log(JSON.stringify({url:base,sourceCommit:evidence.release.sourceCommit,resources:evidence.resources.length,browser:evidence.browser,input:'create, physical lamp repair, keyboard movement',errors:evidence.errors}));
}finally{await browser.close();}
